/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: '🏗️ Architecture',
      items: [{ type: 'autogenerated', dirName: 'architecture' }],
    },
    {
      type: 'category',
      label: '🔌 APIs',
      items: [{ type: 'autogenerated', dirName: 'apis' }],
    },
    {
      type: 'category',
      label: '⚙️ Workflows',
      items: [{ type: 'autogenerated', dirName: 'workflows' }],
    },
    {
      type: 'category',
      label: '🚀 Onboarding',
      items: [{ type: 'autogenerated', dirName: 'onboarding' }],
    },
    {
      type: 'category',
      label: '📋 Décisions (ADR)',
      items: [{ type: 'autogenerated', dirName: 'decisions' }],
    },
  ],
};

export default sidebars;