/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export const velotafSidebar = {
  velotafSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: '🧠 Comprendre le projet',
      items: [{ type: 'autogenerated', dirName: 'comprendre' }],
    },
    {
      type: 'category',
      label: '🏗️ Infrastructure',
      items: [{ type: 'autogenerated', dirName: 'infrastructure' }],
    },
    {
      type: 'category',
      label: '📋 Décisions (ADR)',
      items: [{ type: 'autogenerated', dirName: 'decisions' }],
    },
  ],
};

export default velotafSidebar;
